import { ThemeConfig } from '../types/theme';

export const defaultThemeConfig: ThemeConfig = {
  colors: {
    theme: '#00D5F6',
    theme2: '#d39a09',
    theme3: '#00D5F6',
    theme4: '#000',
    body: '#fff',
    black: '#000',
    white: '#eee',
    header: '#0D1224',
    text: '#7d7d7d',
    border: '#D4DCFF',
    border2: '#D4DCED',
    bg: '#222',
    bg2: '#1A1A1A',
    // Additional color variables
    primaryColor: '#007bff',
    primaryColorHover: '#0056b3',
    secondaryColor: '#6c757d',
    successColor: '#28a745',
    dangerColor: '#dc3545',
    warningColor: '#ffc107',
    infoColor: '#17a2b8',
    lightColor: '#f8f9fa',
    darkColor: '#343a40',
  },
  typography: {
    fontFamily: '"Barlow Condensed", sans-serif',
    fontFamilyBase: '"Barlow Condensed", BlinkMacSystemFont, \'Segoe UI\', Roboto, \'Helvetica Neue\', Arial, sans-serif',
    fontSizeBase: '1rem',
    lineHeightBase: 1.5,
    fontSizeH1: '72px',
    fontSizeH2: '40px',
    fontSizeH3: '24px',
    fontSizeH4: '20px',
    fontSizeH5: '18px',
    fontSizeH6: '16px',
    fontSizeUp1: '1.5rem',
    fontSizeUp2: '2rem',
    fontSizeUp3: '2.5rem',
    fontSizeUp4: '3rem',
    fontSizeUp5: '3.5rem',
    fontSizeUp6: '4rem',
  },
  spacing: {
    xs: '0.25rem',
    sm: '0.5rem',
    md: '1rem',
    lg: '1.5rem',
    xl: '3rem',
  },
  borderRadius: {
    default: '0.375rem',
    lg: '0.5rem',
    sm: '0.25rem',
  },
  shadows: {
    default: '0px 1px 14px 0px rgba(0, 0, 0, 0.13)',
    lg: '0 0.5rem 1rem rgba(0, 0, 0, 0.15)',
    bootstrap: '0 0.125rem 0.25rem rgba(0, 0, 0, 0.075)',
  },
  assets: {
    logoUrl: '/assets/img/logo/white-logo.png',
    breadcrumbBackgroundUrl: '/assets/img/breadcrumb-bg.jpg',
  },
}; 